
- name: ACM Fence Primary
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Fence the Primary managed Cluster
      ansible.builtin.debug:
        msg: "Primary cluster is being fenched."

    - name: Fence the Primary managed cluster
      redhat.openshift.k8s:
        state: patched
        definition:
          kind: DRCluster
          name: dr-cluster5  # TODO get it from event.
          spec:
            clusterFence: Fenced


