---
- name: Interact with OpenShift
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create an OCP project
      redhat.openshift.k8s:
        state: absent
        resource_definition:
          apiVersion: project.openshift.io/v1
          kind: Project
          metadata:
            name: ns1
